# Site settings
title: Tadeusz Rychter's blog
description: > # this means to ignore newlines until "baseurl:"
  Techblog of a frontend developer - Tadeusz Rychter
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site
twitter_username:
github_username:  TadeuszRychter

# Build settings
markdown: kramdown
exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: pygments

# YB Settings
excerpt_separator: <!-- more -->
paginate: 4
comments: true
